name: Build and Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        type: [Debug, RelWithDebInfo]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Configure
        run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.type }}
      - name: Build
        run: cmake --build . --config ${{ matrix.type }}
      - name: Test
        run: ctest -C ${{ matrix.type }} --output-on-failure
